"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['data.txt', 'logo.png', "./png wallpapers/AppBreweryWallpaper 2.png",
              "./png wallpapers/AppBreweryWallpaper 3.png",
              "./png wallpapers/AppBreweryWallpaper 4.png",
              "./png wallpapers/AppBreweryWallpaper 5.png",
              "./png wallpapers/AppBreweryWallpaper 6.png",
              "./png wallpapers/AppBreweryWallpaper 7.png",
              "./png wallpapers/AppBreweryWallpaper 8.png",
              "./png wallpapers/AppBreweryWallpaper 9.png",
              ]
OPTIONS = {'argv_emulation': True,
           # 'packages': ['certifi']
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


